apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-shared-ecr-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  local:
    path: /asrc/ecr/danielv/kubestorage/ecr
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ariel3
          - ariel6
          - ariel7
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-shared-ecr-pvc
spec:
  accessModes:
  - ReadOnlyMany
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-scratch-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  local:
    path: /scratch/airflow
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ariel3
          - ariel6
          - ariel7
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-scratch-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 100Gi
